url: https://alfredshirts.com
baseurl: /alfredshirts.com/

# Site settings
title: Alfred Shirts
email: charliemoonen@gmail.com
description: "I'm alfred, an alpaca that makes shirts! hmmmmmmmm-SCREE-HAW!"


# Team names, titles and social links
people:
- name: Alfred
  pic: 1
  position: Mascot

- name: Charles Moonen
  pic: 2
  position: Designer, Printer, Shipper.
  social:
    - title: twitter
      url: https://twitter.com/charliemoonen
    - title: github
      url: https://github.com/turnipjs

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# none

# Postal address (add as many lines as necessary)
address:
  - line: 715 Harriet Ave
  - line: Shoreview, MN 55126

# Build settings
markdown: kramdown
permalink: pretty
